[package]
name = "mandelbrot-viewer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
egui = "0.36.1"
egui-wgpu = "0.36.1"
egui-winit = "0.36.1"
env_logger = "0.11.11"
log = "0.4.34"
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30.13"
winresource = "0.1.31"

[build-dependencies]
winresource = "0.1.31"